### ISSUE TITLE
Can you provide a complete wiring diagram of the circuit board?

### ISSUE THREAD

**Issue by sevenberyl** [ChikaraWakaura/i2sDinDisp#1]
Great example！
My pcm1808 doesn't work and I want to know how to connect esp32。

Can you provide a complete wiring diagram of the circuit board?

Thank you！

**Comment by ChikaraWakaura** [comment]
hello. Unfortunately, there is no circuit that shows the whole thing. The connection with the ESP32 is as shown in "Connecting the PCM1808 board with the esp32".
